#!/bin/sh
while read file
do
        case "$1" in
	"C-d") rm -rf "$file" ;;
	"1") mkdir -p 1 && mv "$file" "$(pwd)/1";;
	"2") mkdir -p 2 && mv "$file" "$(pwd)/2";;
	"3") mkdir -p 3 && mv "$file" "$(pwd)/3";;
	"4") mkdir -p 4 && mv "$file" "$(pwd)/4";;
	"5") mkdir -p 5 && mv "$file" "$(pwd)/5";;
        "C-b")
             cp "$file" ~/Dropbox ;;
        "C-r")
             convert -rotate 90 "$file" "$file" ;;
        "C-y")
	     xclip -selection clipboard "$file" -t image/png;;
        "C-w")
                nitrogen --save --set-zoom-fill "$file" ;;
        esac
done
